# -*- coding: utf-8 -*-
"""Vendas - Prever qualidade de veiculos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w9OpwP-BnAbNCdGw-VUobe_KMnODhbqL
"""

import pandas as pd
from io import StringIO
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

# String que contém os dados
dados_veiculos_str = """
ID,Exigencia_Manutencao,Portas,Porta_Malas_L,Seguranca,Qualidade_Risco
1,Baixa,4,400,8,Baixo
2,Media,2,250,6,Medio
3,Alta,4,350,4,Alto
4,Baixa,4,500,9,Baixo
5,Media,5,300,7,Medio
6,Alta,2,200,3,Alto
7,Baixa,5,450,10,Baixo
8,Media,4,380,5,Medio
9,Alta,2,220,2,Alto
10,Baixa,4,480,9,Baixo
11,Media,5,320,6,Medio
12,Alta,4,300,4,Alto
13,Baixa,2,280,7,Baixo
14,Media,4,340,6,Medio
15,Alta,5,420,5,Alto
"""

df_veiculos = pd.read_csv(StringIO(dados_veiculos_str))

# Mapeamento e Codificação (Label Encoding)
mapeamento_manutencao = {'Baixa': 1, 'Media': 2, 'Alta': 3}
mapeamento_risco = {'Baixo': 0, 'Medio': 1, 'Alto': 2} # O target deve ser numérico

df_veiculos['Exigencia_Manutencao_Cod'] = df_veiculos['Exigencia_Manutencao'].map(mapeamento_manutencao)
df_veiculos['Qualidade_Risco_Cod'] = df_veiculos['Qualidade_Risco'].map(mapeamento_risco)

# Define Features (X) e Target (y)
X = df_veiculos[['Exigencia_Manutencao_Cod', 'Portas', 'Porta_Malas_L', 'Seguranca']]
y = df_veiculos['Qualidade_Risco_Cod']

# Treinamento (usando todo o conjunto devido ao tamanho)
model_rf = RandomForestClassifier(n_estimators=100, random_state=42)
model_rf.fit(X, y)

print("--- DataFrame de Veículos e Codificação Concluída ---")
print(df_veiculos[['Exigencia_Manutencao', 'Exigencia_Manutencao_Cod', 'Qualidade_Risco', 'Qualidade_Risco_Cod']].head())
print("\nTreinamento do Classificador Random Forest concluído.")

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from io import StringIO

# --- Recriação do Ambiente (Mapeamentos e Modelo Treinado) ---
# Mapeamentos usados no treinamento (Média = 2)
mapeamento_manutencao = {'Baixa': 1, 'Media': 2, 'Alta': 3}
mapeamento_risco = {0: 'Baixo', 1: 'Medio', 2: 'Alto'}

# Dados simulados do novo veículo
novo_veiculo_data = {
    'Exigencia_Manutencao_Cod': [mapeamento_manutencao['Media']],
    'Portas': [5],
    'Porta_Malas_L': [350],
    'Seguranca': [8]
}
df_novo = pd.DataFrame(novo_veiculo_data)

# Recriando um modelo treinado (usando a Importância das Features para simular o treinamento)
# Este é um passo essencial que você deve garantir no seu notebook real.
# Na simulação, precisamos do modelo treinado para prever.
# Usamos o resultado do treinamento anterior (100% acurácia)

dados_veiculos_str = """
ID,Exigencia_Manutencao,Portas,Porta_Malas_L,Seguranca,Qualidade_Risco
1,Baixa,4,400,8,Baixo
2,Media,2,250,6,Medio
3,Alta,4,350,4,Alto
4,Baixa,4,500,9,Baixo
5,Media,5,300,7,Medio
6,Alta,2,200,3,Alto
7,Baixa,5,450,10,Baixo
8,Media,4,380,5,Medio
9,Alta,2,220,2,Alto
10,Baixa,4,480,9,Baixo
11,Media,5,320,6,Medio
12,Alta,4,300,4,Alto
13,Baixa,2,280,7,Baixo
14,Media,4,340,6,Medio
15,Alta,5,420,5,Alto
"""
df_veiculos = pd.read_csv(StringIO(dados_veiculos_str))
df_veiculos['Exigencia_Manutencao_Cod'] = df_veiculos['Exigencia_Manutencao'].map(mapeamento_manutencao)
df_veiculos['Qualidade_Risco_Cod'] = df_veiculos['Qualidade_Risco'].map({v: k for k, v in mapeamento_risco.items()})
X = df_veiculos[['Exigencia_Manutencao_Cod', 'Portas', 'Porta_Malas_L', 'Seguranca']]
y = df_veiculos['Qualidade_Risco_Cod']
model_rf = RandomForestClassifier(n_estimators=100, random_state=42)
model_rf.fit(X, y)


# Previsão do Risco
previsao_cod = model_rf.predict(df_novo)[0]
previsao_risco = mapeamento_risco[previsao_cod]


# Previsão das Probabilidades (Avaliando a Confiança)
# O Random Forest fornece a probabilidade de pertencer a cada classe
probabilidades = model_rf.predict_proba(df_novo)[0]
prob_df = pd.DataFrame(
    {'Risco': list(mapeamento_risco.values()),
     'Probabilidade': probabilidades}
).sort_values(by='Probabilidade', ascending=False)


print("--- Previsão de Qualidade/Risco ---")
print(f"Risco de Manutenção Previsto: **{previsao_risco}**")
print("-----------------------------------")
print("\n--- Probabilidades de Classe (Confiança) ---")
print(prob_df)